### ISSUE TITLE
'sass' command not found

### ISSUE THREAD

**Issue by valter-silva-au** [ejisan/play-simple-web#1]
Hi, 
I'm trying out your template via Lightbend UI. And after cloning and starting the project, I got the following error.

`'sass' command not found. Try to add path to 'sass' to your $PATH system variable`

Coud you please advise ? 

Thanks!

**Comment by ejisan** [comment]
This template was using "sbt-sass" plugin, and it requires "sass" your computer to be installed.
[Install SASS and compass](http://thesassway.com/beginner/getting-started-with-sass-and-compass) (For compiling Foundation you need to install compass)

**Comment by ejisan** [comment]
Since Play Framework 2.5.x it officially added the sass plugin `sbt-sassify`.
I updated this template today. Now you can use latest play framework and foundation without installing `sass` and `compass` by refetching this template.

**Comment by valter-silva-au** [comment]
I have tried again today and it worked, thank you!
